---
- name: Deploy traefik-kop
  hosts: traefik_kop

  tasks:
    - name: Include variables
      ansible.builtin.include_vars: secrets.yml

    - name: Deploy traefik-kop
      ansible.builtin.include_role:
        name: joshrnoll.homelab.tailscale_container
      vars:
        tailscale_container_tailnet_name: "{{ tailnet_name }}"
        tailscale_container_oauth_client_secret: "{{ tailscale_containers_oauth_client['secret'] }}"
        tailscale_container_service_name: traefik-kop-{{ ansible_facts['nodename'] }}
        tailscale_container_image: ghcr.io/jittering/traefik-kop
        tailscale_container_tag: 0.14.1-next-1978118-amd64 # Use 0.14.1-next-1978118-arm64v8 for raspberry pi or other ARM based systems
        tailscale_container_no_serve: true
        tailscale_container_userspace_networking: "false"
        tailscale_container_volumes:
           - /var/run/docker.sock:/var/run/docker.sock
        tailscale_container_env_vars:
          REDIS_ADDR: "redis-traefik.{{ tailnet_name }}:6379"
          BIND_IP: "{{ ansible_facts['tailscale0']['ipv4']['address'] }}"
...